// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct AMapLatLngDTO: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AMapLatLngDTO? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return AMapLatLngDTO(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: AMapLatLngDTO, rhs: AMapLatLngDTO) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AMapLatLngDTO")
    MessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "AMapLatLngDTO(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AMapRouteInfoDTO: Hashable, CustomStringConvertible {
  var routeLength: Int64
  var routeTime: Int64
  var routeSegmentCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AMapRouteInfoDTO? {
    let routeLength = pigeonVar_list[0] as! Int64
    let routeTime = pigeonVar_list[1] as! Int64
    let routeSegmentCount = pigeonVar_list[2] as! Int64

    return AMapRouteInfoDTO(
      routeLength: routeLength,
      routeTime: routeTime,
      routeSegmentCount: routeSegmentCount
    )
  }
  func toList() -> [Any?] {
    return [
      routeLength,
      routeTime,
      routeSegmentCount,
    ]
  }
  static func == (lhs: AMapRouteInfoDTO, rhs: AMapRouteInfoDTO) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.routeLength, rhs.routeLength) && MessagesPigeonInternal.deepEquals(lhs.routeTime, rhs.routeTime) && MessagesPigeonInternal.deepEquals(lhs.routeSegmentCount, rhs.routeSegmentCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AMapRouteInfoDTO")
    MessagesPigeonInternal.deepHash(value: routeLength, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: routeTime, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: routeSegmentCount, hasher: &hasher)
  }

  public var description: String {
    return "AMapRouteInfoDTO(routeLength: \(String(describing: routeLength)), routeTime: \(String(describing: routeTime)), routeSegmentCount: \(String(describing: routeSegmentCount)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AMapRouteFailureDTO: Hashable, CustomStringConvertible {
  var code: Int64
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AMapRouteFailureDTO? {
    let code = pigeonVar_list[0] as! Int64
    let message = pigeonVar_list[1] as! String

    return AMapRouteFailureDTO(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: AMapRouteFailureDTO, rhs: AMapRouteFailureDTO) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AMapRouteFailureDTO")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "AMapRouteFailureDTO(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AMapNaviInfoDTO: Hashable, CustomStringConvertible {
  var routeRemainDistance: Int64
  var routeRemainTime: Int64
  var segmentRemainDistance: Int64
  var segmentRemainTime: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AMapNaviInfoDTO? {
    let routeRemainDistance = pigeonVar_list[0] as! Int64
    let routeRemainTime = pigeonVar_list[1] as! Int64
    let segmentRemainDistance = pigeonVar_list[2] as! Int64
    let segmentRemainTime = pigeonVar_list[3] as! Int64

    return AMapNaviInfoDTO(
      routeRemainDistance: routeRemainDistance,
      routeRemainTime: routeRemainTime,
      segmentRemainDistance: segmentRemainDistance,
      segmentRemainTime: segmentRemainTime
    )
  }
  func toList() -> [Any?] {
    return [
      routeRemainDistance,
      routeRemainTime,
      segmentRemainDistance,
      segmentRemainTime,
    ]
  }
  static func == (lhs: AMapNaviInfoDTO, rhs: AMapNaviInfoDTO) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.routeRemainDistance, rhs.routeRemainDistance) && MessagesPigeonInternal.deepEquals(lhs.routeRemainTime, rhs.routeRemainTime) && MessagesPigeonInternal.deepEquals(lhs.segmentRemainDistance, rhs.segmentRemainDistance) && MessagesPigeonInternal.deepEquals(lhs.segmentRemainTime, rhs.segmentRemainTime)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AMapNaviInfoDTO")
    MessagesPigeonInternal.deepHash(value: routeRemainDistance, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: routeRemainTime, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: segmentRemainDistance, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: segmentRemainTime, hasher: &hasher)
  }

  public var description: String {
    return "AMapNaviInfoDTO(routeRemainDistance: \(String(describing: routeRemainDistance)), routeRemainTime: \(String(describing: routeRemainTime)), segmentRemainDistance: \(String(describing: segmentRemainDistance)), segmentRemainTime: \(String(describing: segmentRemainTime)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AMapRouteStyleDTO: Hashable, CustomStringConvertible {
  var lineWidth: Double
  var lineColor: Int64
  var showStartEndMarker: Bool
  var startMarkerColor: Int64
  var endMarkerColor: Int64
  var startTitle: String
  var endTitle: String
  var textureBytes: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AMapRouteStyleDTO? {
    let lineWidth = pigeonVar_list[0] as! Double
    let lineColor = pigeonVar_list[1] as! Int64
    let showStartEndMarker = pigeonVar_list[2] as! Bool
    let startMarkerColor = pigeonVar_list[3] as! Int64
    let endMarkerColor = pigeonVar_list[4] as! Int64
    let startTitle = pigeonVar_list[5] as! String
    let endTitle = pigeonVar_list[6] as! String
    let textureBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[7])

    return AMapRouteStyleDTO(
      lineWidth: lineWidth,
      lineColor: lineColor,
      showStartEndMarker: showStartEndMarker,
      startMarkerColor: startMarkerColor,
      endMarkerColor: endMarkerColor,
      startTitle: startTitle,
      endTitle: endTitle,
      textureBytes: textureBytes
    )
  }
  func toList() -> [Any?] {
    return [
      lineWidth,
      lineColor,
      showStartEndMarker,
      startMarkerColor,
      endMarkerColor,
      startTitle,
      endTitle,
      textureBytes,
    ]
  }
  static func == (lhs: AMapRouteStyleDTO, rhs: AMapRouteStyleDTO) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.lineWidth, rhs.lineWidth) && MessagesPigeonInternal.deepEquals(lhs.lineColor, rhs.lineColor) && MessagesPigeonInternal.deepEquals(lhs.showStartEndMarker, rhs.showStartEndMarker) && MessagesPigeonInternal.deepEquals(lhs.startMarkerColor, rhs.startMarkerColor) && MessagesPigeonInternal.deepEquals(lhs.endMarkerColor, rhs.endMarkerColor) && MessagesPigeonInternal.deepEquals(lhs.startTitle, rhs.startTitle) && MessagesPigeonInternal.deepEquals(lhs.endTitle, rhs.endTitle) && MessagesPigeonInternal.deepEquals(lhs.textureBytes, rhs.textureBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AMapRouteStyleDTO")
    MessagesPigeonInternal.deepHash(value: lineWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lineColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showStartEndMarker, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startMarkerColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endMarkerColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: textureBytes, hasher: &hasher)
  }

  public var description: String {
    return "AMapRouteStyleDTO(lineWidth: \(String(describing: lineWidth)), lineColor: \(String(describing: lineColor)), showStartEndMarker: \(String(describing: showStartEndMarker)), startMarkerColor: \(String(describing: startMarkerColor)), endMarkerColor: \(String(describing: endMarkerColor)), startTitle: \(String(describing: startTitle)), endTitle: \(String(describing: endTitle)), textureBytes: \(String(describing: textureBytes)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AMapLatLngDTO.fromList(self.readValue() as! [Any?])
    case 130:
      return AMapRouteInfoDTO.fromList(self.readValue() as! [Any?])
    case 131:
      return AMapRouteFailureDTO.fromList(self.readValue() as! [Any?])
    case 132:
      return AMapNaviInfoDTO.fromList(self.readValue() as! [Any?])
    case 133:
      return AMapRouteStyleDTO.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AMapLatLngDTO {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AMapRouteInfoDTO {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AMapRouteFailureDTO {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AMapNaviInfoDTO {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AMapRouteStyleDTO {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AMapNavigatorApi {
  func initializeNavigationSession() throws
  func cleanupNavigationSession() throws
  func calculateWalkRoute(start: AMapLatLngDTO, end: AMapLatLngDTO) throws -> Bool
  func startGpsNavi() throws
  func stopNavi() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AMapNavigatorApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AMapNavigatorApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AMapNavigatorApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeNavigationSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.initializeNavigationSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeNavigationSessionChannel.setMessageHandler { _, reply in
        do {
          try api.initializeNavigationSession()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeNavigationSessionChannel.setMessageHandler(nil)
    }
    let cleanupNavigationSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.cleanupNavigationSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cleanupNavigationSessionChannel.setMessageHandler { _, reply in
        do {
          try api.cleanupNavigationSession()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cleanupNavigationSessionChannel.setMessageHandler(nil)
    }
    let calculateWalkRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.calculateWalkRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      calculateWalkRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let startArg = args[0] as! AMapLatLngDTO
        let endArg = args[1] as! AMapLatLngDTO
        do {
          let result = try api.calculateWalkRoute(start: startArg, end: endArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      calculateWalkRouteChannel.setMessageHandler(nil)
    }
    let startGpsNaviChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.startGpsNavi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGpsNaviChannel.setMessageHandler { _, reply in
        do {
          try api.startGpsNavi()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startGpsNaviChannel.setMessageHandler(nil)
    }
    let stopNaviChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.stopNavi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopNaviChannel.setMessageHandler { _, reply in
        do {
          try api.stopNavi()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopNaviChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AMapViewApi {
  func showCurrentWalkRoute(viewId: Int64, style: AMapRouteStyleDTO) throws -> Bool
  func clearRoute(viewId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AMapViewApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AMapViewApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AMapViewApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let showCurrentWalkRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapViewApi.showCurrentWalkRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showCurrentWalkRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let styleArg = args[1] as! AMapRouteStyleDTO
        do {
          let result = try api.showCurrentWalkRoute(viewId: viewIdArg, style: styleArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showCurrentWalkRouteChannel.setMessageHandler(nil)
    }
    let clearRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapViewApi.clearRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          try api.clearRoute(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearRouteChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AMapNavigatorEventApiProtocol {
  func onNaviStarted(naviMode naviModeArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onNaviStopped(isStopped isStoppedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRouteCalculateSuccess(routeInfo routeInfoArg: AMapRouteInfoDTO, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRouteCalculateFailure(failure failureArg: AMapRouteFailureDTO, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGpsSignalUpdated(strength strengthArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRerouteForYaw(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTtsText(text textArg: String, soundType soundTypeArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onNaviInfoUpdated(naviInfo naviInfoArg: AMapNaviInfoDTO, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AMapNavigatorEventApi: AMapNavigatorEventApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onNaviStarted(naviMode naviModeArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([naviModeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onNaviStopped(isStopped isStoppedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isStoppedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRouteCalculateSuccess(routeInfo routeInfoArg: AMapRouteInfoDTO, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRouteCalculateSuccess\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([routeInfoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRouteCalculateFailure(failure failureArg: AMapRouteFailureDTO, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRouteCalculateFailure\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([failureArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onGpsSignalUpdated(strength strengthArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onGpsSignalUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([strengthArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRerouteForYaw(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRerouteForYaw\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onTtsText(text textArg: String, soundType soundTypeArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onTtsText\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg, soundTypeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onNaviInfoUpdated(naviInfo naviInfoArg: AMapNaviInfoDTO, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviInfoUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([naviInfoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AMapServicesApi {
  func setAppKey(appKey: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AMapServicesApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AMapServicesApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AMapServicesApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setAppKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapServicesApi.setAppKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAppKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appKeyArg = args[0] as! String
        do {
          try api.setAppKey(appKey: appKeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAppKeyChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AMapNaviConfigApi {
  func areTermsAccepted() throws -> Bool
  func setTermsAccepted(accepted: Bool) throws
  func updatePrivacyShow(hasShow: Bool, hasContains: Bool) throws
  func updatePrivacyAgree(hasAgree: Bool) throws
  func setSpeechRate(speechRate: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AMapNaviConfigApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AMapNaviConfigApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AMapNaviConfigApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let areTermsAcceptedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.areTermsAccepted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      areTermsAcceptedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.areTermsAccepted()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      areTermsAcceptedChannel.setMessageHandler(nil)
    }
    let setTermsAcceptedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.setTermsAccepted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTermsAcceptedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let acceptedArg = args[0] as! Bool
        do {
          try api.setTermsAccepted(accepted: acceptedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTermsAcceptedChannel.setMessageHandler(nil)
    }
    let updatePrivacyShowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.updatePrivacyShow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePrivacyShowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let hasShowArg = args[0] as! Bool
        let hasContainsArg = args[1] as! Bool
        do {
          try api.updatePrivacyShow(hasShow: hasShowArg, hasContains: hasContainsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePrivacyShowChannel.setMessageHandler(nil)
    }
    let updatePrivacyAgreeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.updatePrivacyAgree\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePrivacyAgreeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let hasAgreeArg = args[0] as! Bool
        do {
          try api.updatePrivacyAgree(hasAgree: hasAgreeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePrivacyAgreeChannel.setMessageHandler(nil)
    }
    let setSpeechRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.setSpeechRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSpeechRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let speechRateArg = args[0] as! Double
        do {
          try api.setSpeechRate(speechRate: speechRateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSpeechRateChannel.setMessageHandler(nil)
    }
  }
}
