// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.amap_navi_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class AMapLatLngDTO (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AMapLatLngDTO {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return AMapLatLngDTO(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AMapLatLngDTO
    return MessagesPigeonUtils.deepEquals(this.latitude, other.latitude) && MessagesPigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "AMapLatLngDTO(latitude=$latitude, longitude=$longitude)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AMapRouteInfoDTO (
  val routeLength: Long,
  val routeTime: Long,
  val routeSegmentCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AMapRouteInfoDTO {
      val routeLength = pigeonVar_list[0] as Long
      val routeTime = pigeonVar_list[1] as Long
      val routeSegmentCount = pigeonVar_list[2] as Long
      return AMapRouteInfoDTO(routeLength, routeTime, routeSegmentCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      routeLength,
      routeTime,
      routeSegmentCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AMapRouteInfoDTO
    return MessagesPigeonUtils.deepEquals(this.routeLength, other.routeLength) && MessagesPigeonUtils.deepEquals(this.routeTime, other.routeTime) && MessagesPigeonUtils.deepEquals(this.routeSegmentCount, other.routeSegmentCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.routeLength)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.routeTime)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.routeSegmentCount)
    return result
  }
  override fun toString(): String {
    return "AMapRouteInfoDTO(routeLength=$routeLength, routeTime=$routeTime, routeSegmentCount=$routeSegmentCount)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AMapRouteFailureDTO (
  val code: Long,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AMapRouteFailureDTO {
      val code = pigeonVar_list[0] as Long
      val message = pigeonVar_list[1] as String
      return AMapRouteFailureDTO(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AMapRouteFailureDTO
    return MessagesPigeonUtils.deepEquals(this.code, other.code) && MessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "AMapRouteFailureDTO(code=$code, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AMapNaviInfoDTO (
  val routeRemainDistance: Long,
  val routeRemainTime: Long,
  val segmentRemainDistance: Long,
  val segmentRemainTime: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AMapNaviInfoDTO {
      val routeRemainDistance = pigeonVar_list[0] as Long
      val routeRemainTime = pigeonVar_list[1] as Long
      val segmentRemainDistance = pigeonVar_list[2] as Long
      val segmentRemainTime = pigeonVar_list[3] as Long
      return AMapNaviInfoDTO(routeRemainDistance, routeRemainTime, segmentRemainDistance, segmentRemainTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      routeRemainDistance,
      routeRemainTime,
      segmentRemainDistance,
      segmentRemainTime,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AMapNaviInfoDTO
    return MessagesPigeonUtils.deepEquals(this.routeRemainDistance, other.routeRemainDistance) && MessagesPigeonUtils.deepEquals(this.routeRemainTime, other.routeRemainTime) && MessagesPigeonUtils.deepEquals(this.segmentRemainDistance, other.segmentRemainDistance) && MessagesPigeonUtils.deepEquals(this.segmentRemainTime, other.segmentRemainTime)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.routeRemainDistance)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.routeRemainTime)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.segmentRemainDistance)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.segmentRemainTime)
    return result
  }
  override fun toString(): String {
    return "AMapNaviInfoDTO(routeRemainDistance=$routeRemainDistance, routeRemainTime=$routeRemainTime, segmentRemainDistance=$segmentRemainDistance, segmentRemainTime=$segmentRemainTime)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AMapRouteStyleDTO (
  val lineWidth: Double,
  val lineColor: Long,
  val showStartEndMarker: Boolean,
  val startMarkerColor: Long,
  val endMarkerColor: Long,
  val startTitle: String,
  val endTitle: String,
  val textureBytes: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AMapRouteStyleDTO {
      val lineWidth = pigeonVar_list[0] as Double
      val lineColor = pigeonVar_list[1] as Long
      val showStartEndMarker = pigeonVar_list[2] as Boolean
      val startMarkerColor = pigeonVar_list[3] as Long
      val endMarkerColor = pigeonVar_list[4] as Long
      val startTitle = pigeonVar_list[5] as String
      val endTitle = pigeonVar_list[6] as String
      val textureBytes = pigeonVar_list[7] as ByteArray?
      return AMapRouteStyleDTO(lineWidth, lineColor, showStartEndMarker, startMarkerColor, endMarkerColor, startTitle, endTitle, textureBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lineWidth,
      lineColor,
      showStartEndMarker,
      startMarkerColor,
      endMarkerColor,
      startTitle,
      endTitle,
      textureBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AMapRouteStyleDTO
    return MessagesPigeonUtils.deepEquals(this.lineWidth, other.lineWidth) && MessagesPigeonUtils.deepEquals(this.lineColor, other.lineColor) && MessagesPigeonUtils.deepEquals(this.showStartEndMarker, other.showStartEndMarker) && MessagesPigeonUtils.deepEquals(this.startMarkerColor, other.startMarkerColor) && MessagesPigeonUtils.deepEquals(this.endMarkerColor, other.endMarkerColor) && MessagesPigeonUtils.deepEquals(this.startTitle, other.startTitle) && MessagesPigeonUtils.deepEquals(this.endTitle, other.endTitle) && MessagesPigeonUtils.deepEquals(this.textureBytes, other.textureBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lineWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lineColor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showStartEndMarker)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startMarkerColor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endMarkerColor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startTitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endTitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.textureBytes)
    return result
  }
  override fun toString(): String {
    return "AMapRouteStyleDTO(lineWidth=$lineWidth, lineColor=$lineColor, showStartEndMarker=$showStartEndMarker, startMarkerColor=$startMarkerColor, endMarkerColor=$endMarkerColor, startTitle=$startTitle, endTitle=$endTitle, textureBytes=${textureBytes?.contentToString()})"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AMapLatLngDTO.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AMapRouteInfoDTO.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AMapRouteFailureDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AMapNaviInfoDTO.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AMapRouteStyleDTO.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AMapLatLngDTO -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AMapRouteInfoDTO -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AMapRouteFailureDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AMapNaviInfoDTO -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AMapRouteStyleDTO -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AMapNavigatorApi {
  fun initializeNavigationSession()
  fun cleanupNavigationSession()
  fun calculateWalkRoute(start: AMapLatLngDTO, end: AMapLatLngDTO): Boolean
  fun startGpsNavi()
  fun stopNavi()

  companion object {
    /** The codec used by AMapNavigatorApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AMapNavigatorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AMapNavigatorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.initializeNavigationSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initializeNavigationSession()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.cleanupNavigationSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cleanupNavigationSession()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.calculateWalkRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startArg = args[0] as AMapLatLngDTO
            val endArg = args[1] as AMapLatLngDTO
            val wrapped: List<Any?> = try {
              listOf(api.calculateWalkRoute(startArg, endArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.startGpsNavi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startGpsNavi()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.stopNavi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopNavi()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AMapViewApi {
  fun showCurrentWalkRoute(viewId: Long, style: AMapRouteStyleDTO): Boolean
  fun clearRoute(viewId: Long)

  companion object {
    /** The codec used by AMapViewApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AMapViewApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AMapViewApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapViewApi.showCurrentWalkRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val styleArg = args[1] as AMapRouteStyleDTO
            val wrapped: List<Any?> = try {
              listOf(api.showCurrentWalkRoute(viewIdArg, styleArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapViewApi.clearRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.clearRoute(viewIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AMapNavigatorEventApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AMapNavigatorEventApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onNaviStarted(naviModeArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(naviModeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onNaviStopped(isStoppedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(isStoppedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRouteCalculateSuccess(routeInfoArg: AMapRouteInfoDTO, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRouteCalculateSuccess$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(routeInfoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRouteCalculateFailure(failureArg: AMapRouteFailureDTO, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRouteCalculateFailure$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(failureArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGpsSignalUpdated(strengthArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onGpsSignalUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(strengthArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRerouteForYaw(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRerouteForYaw$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onTtsText(textArg: String, soundTypeArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onTtsText$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(textArg, soundTypeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onNaviInfoUpdated(naviInfoArg: AMapNaviInfoDTO, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviInfoUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(naviInfoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AMapServicesApi {
  fun setAppKey(appKey: String)

  companion object {
    /** The codec used by AMapServicesApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AMapServicesApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AMapServicesApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapServicesApi.setAppKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setAppKey(appKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AMapNaviConfigApi {
  fun areTermsAccepted(): Boolean
  fun setTermsAccepted(accepted: Boolean)
  fun updatePrivacyShow(hasShow: Boolean, hasContains: Boolean)
  fun updatePrivacyAgree(hasAgree: Boolean)
  fun setSpeechRate(speechRate: Double)

  companion object {
    /** The codec used by AMapNaviConfigApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AMapNaviConfigApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AMapNaviConfigApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.areTermsAccepted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.areTermsAccepted())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.setTermsAccepted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val acceptedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setTermsAccepted(acceptedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.updatePrivacyShow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hasShowArg = args[0] as Boolean
            val hasContainsArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.updatePrivacyShow(hasShowArg, hasContainsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.updatePrivacyAgree$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hasAgreeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.updatePrivacyAgree(hasAgreeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.setSpeechRate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speechRateArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setSpeechRate(speechRateArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
