// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class AMapLatLngDTO {
  AMapLatLngDTO({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  Object encode() {
    return _toList();  }

  static AMapLatLngDTO decode(Object result) {
    result as List<Object?>;
    return AMapLatLngDTO(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AMapLatLngDTO || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AMapLatLngDTO(latitude: $latitude, longitude: $longitude)';
  }
}

class AMapRouteInfoDTO {
  AMapRouteInfoDTO({
    required this.routeLength,
    required this.routeTime,
    required this.routeSegmentCount,
  });

  int routeLength;

  int routeTime;

  int routeSegmentCount;

  List<Object?> _toList() {
    return <Object?>[
      routeLength,
      routeTime,
      routeSegmentCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static AMapRouteInfoDTO decode(Object result) {
    result as List<Object?>;
    return AMapRouteInfoDTO(
      routeLength: result[0]! as int,
      routeTime: result[1]! as int,
      routeSegmentCount: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AMapRouteInfoDTO || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(routeLength, other.routeLength) && _deepEquals(routeTime, other.routeTime) && _deepEquals(routeSegmentCount, other.routeSegmentCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AMapRouteInfoDTO(routeLength: $routeLength, routeTime: $routeTime, routeSegmentCount: $routeSegmentCount)';
  }
}

class AMapRouteFailureDTO {
  AMapRouteFailureDTO({
    required this.code,
    required this.message,
  });

  int code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static AMapRouteFailureDTO decode(Object result) {
    result as List<Object?>;
    return AMapRouteFailureDTO(
      code: result[0]! as int,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AMapRouteFailureDTO || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AMapRouteFailureDTO(code: $code, message: $message)';
  }
}

class AMapNaviInfoDTO {
  AMapNaviInfoDTO({
    required this.routeRemainDistance,
    required this.routeRemainTime,
    required this.segmentRemainDistance,
    required this.segmentRemainTime,
  });

  int routeRemainDistance;

  int routeRemainTime;

  int segmentRemainDistance;

  int segmentRemainTime;

  List<Object?> _toList() {
    return <Object?>[
      routeRemainDistance,
      routeRemainTime,
      segmentRemainDistance,
      segmentRemainTime,
    ];
  }

  Object encode() {
    return _toList();  }

  static AMapNaviInfoDTO decode(Object result) {
    result as List<Object?>;
    return AMapNaviInfoDTO(
      routeRemainDistance: result[0]! as int,
      routeRemainTime: result[1]! as int,
      segmentRemainDistance: result[2]! as int,
      segmentRemainTime: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AMapNaviInfoDTO || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(routeRemainDistance, other.routeRemainDistance) && _deepEquals(routeRemainTime, other.routeRemainTime) && _deepEquals(segmentRemainDistance, other.segmentRemainDistance) && _deepEquals(segmentRemainTime, other.segmentRemainTime);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AMapNaviInfoDTO(routeRemainDistance: $routeRemainDistance, routeRemainTime: $routeRemainTime, segmentRemainDistance: $segmentRemainDistance, segmentRemainTime: $segmentRemainTime)';
  }
}

class AMapRouteStyleDTO {
  AMapRouteStyleDTO({
    required this.lineWidth,
    required this.lineColor,
    required this.showStartEndMarker,
    required this.startMarkerColor,
    required this.endMarkerColor,
    required this.startTitle,
    required this.endTitle,
    this.textureBytes,
  });

  double lineWidth;

  int lineColor;

  bool showStartEndMarker;

  int startMarkerColor;

  int endMarkerColor;

  String startTitle;

  String endTitle;

  Uint8List? textureBytes;

  List<Object?> _toList() {
    return <Object?>[
      lineWidth,
      lineColor,
      showStartEndMarker,
      startMarkerColor,
      endMarkerColor,
      startTitle,
      endTitle,
      textureBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static AMapRouteStyleDTO decode(Object result) {
    result as List<Object?>;
    return AMapRouteStyleDTO(
      lineWidth: result[0]! as double,
      lineColor: result[1]! as int,
      showStartEndMarker: result[2]! as bool,
      startMarkerColor: result[3]! as int,
      endMarkerColor: result[4]! as int,
      startTitle: result[5]! as String,
      endTitle: result[6]! as String,
      textureBytes: result[7] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AMapRouteStyleDTO || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lineWidth, other.lineWidth) && _deepEquals(lineColor, other.lineColor) && _deepEquals(showStartEndMarker, other.showStartEndMarker) && _deepEquals(startMarkerColor, other.startMarkerColor) && _deepEquals(endMarkerColor, other.endMarkerColor) && _deepEquals(startTitle, other.startTitle) && _deepEquals(endTitle, other.endTitle) && _deepEquals(textureBytes, other.textureBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AMapRouteStyleDTO(lineWidth: $lineWidth, lineColor: $lineColor, showStartEndMarker: $showStartEndMarker, startMarkerColor: $startMarkerColor, endMarkerColor: $endMarkerColor, startTitle: $startTitle, endTitle: $endTitle, textureBytes: $textureBytes)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AMapLatLngDTO) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AMapRouteInfoDTO) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is AMapRouteFailureDTO) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AMapNaviInfoDTO) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AMapRouteStyleDTO) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AMapLatLngDTO.decode(readValue(buffer)!);
      case 130:
        return AMapRouteInfoDTO.decode(readValue(buffer)!);
      case 131:
        return AMapRouteFailureDTO.decode(readValue(buffer)!);
      case 132:
        return AMapNaviInfoDTO.decode(readValue(buffer)!);
      case 133:
        return AMapRouteStyleDTO.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AMapNavigatorApi {
  /// Constructor for [AMapNavigatorApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AMapNavigatorApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initializeNavigationSession() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.initializeNavigationSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cleanupNavigationSession() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.cleanupNavigationSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> calculateWalkRoute(AMapLatLngDTO start, AMapLatLngDTO end) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.calculateWalkRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[start, end]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startGpsNavi() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.startGpsNavi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopNavi() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorApi.stopNavi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

class AMapViewApi {
  /// Constructor for [AMapViewApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AMapViewApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> showCurrentWalkRoute(int viewId, AMapRouteStyleDTO style) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapViewApi.showCurrentWalkRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId, style]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> clearRoute(int viewId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapViewApi.clearRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class AMapNavigatorEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onNaviStarted(int naviMode);

  void onNaviStopped(bool isStopped);

  void onRouteCalculateSuccess(AMapRouteInfoDTO routeInfo);

  void onRouteCalculateFailure(AMapRouteFailureDTO failure);

  void onGpsSignalUpdated(int strength);

  void onRerouteForYaw();

  void onTtsText(String text, int soundType);

  void onNaviInfoUpdated(AMapNaviInfoDTO naviInfo);

  static void setUp(AMapNavigatorEventApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_naviMode = args[0]! as int;
          try {
            api.onNaviStarted(arg_naviMode);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_isStopped = args[0]! as bool;
          try {
            api.onNaviStopped(arg_isStopped);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRouteCalculateSuccess$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AMapRouteInfoDTO arg_routeInfo = args[0]! as AMapRouteInfoDTO;
          try {
            api.onRouteCalculateSuccess(arg_routeInfo);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRouteCalculateFailure$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AMapRouteFailureDTO arg_failure = args[0]! as AMapRouteFailureDTO;
          try {
            api.onRouteCalculateFailure(arg_failure);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onGpsSignalUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_strength = args[0]! as int;
          try {
            api.onGpsSignalUpdated(arg_strength);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onRerouteForYaw$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onRerouteForYaw();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onTtsText$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_text = args[0]! as String;
          final int arg_soundType = args[1]! as int;
          try {
            api.onTtsText(arg_text, arg_soundType);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.amap_navi_flutter.AMapNavigatorEventApi.onNaviInfoUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AMapNaviInfoDTO arg_naviInfo = args[0]! as AMapNaviInfoDTO;
          try {
            api.onNaviInfoUpdated(arg_naviInfo);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class AMapServicesApi {
  /// Constructor for [AMapServicesApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AMapServicesApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setAppKey(String appKey) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapServicesApi.setAppKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[appKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

class AMapNaviConfigApi {
  /// Constructor for [AMapNaviConfigApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AMapNaviConfigApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> areTermsAccepted() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.areTermsAccepted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setTermsAccepted(bool accepted) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.setTermsAccepted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[accepted]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> updatePrivacyShow(bool hasShow, bool hasContains) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.updatePrivacyShow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[hasShow, hasContains]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> updatePrivacyAgree(bool hasAgree) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.updatePrivacyAgree$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[hasAgree]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setSpeechRate(double speechRate) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amap_navi_flutter.AMapNaviConfigApi.setSpeechRate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[speechRate]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
